- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create network
    azure_rm_virtualnetwork:
       resource_group: "{{ rs_group }}"
       name: "{{ vnet_name }}"
       address_prefixes: "{{ address_prefix }}"

  - name: Add subnet
    azure_rm_subnet:
       resource_group: "{{ rs_group }}"
       name: "subnet1"
       address_prefix: "{{ subnet_address_prefix }}"
       virtual_network: "{{ vnet_name }}"

  - name: Create public ip
    azure_rm_publicipaddress:
       resource_group: "{{ rs_group }}"
       allocation_method: Static
       name: "{{ 'publicip' + vnet_name }}"
    when:  public_ip_required  == "True"

  - name: Create security group that allows SSH
    azure_rm_securitygroup:
       resource_group: "{{ rs_group }}"
       name: "{{ sec_gr_name }}"
       rules:
         - name: SSH
           protocol: Tcp
           destination_port_range: 22
           access: Allow
           priority: 101
           direction: Inbound

  - name: Create NIC
    azure_rm_networkinterface:
        resource_group: "{{ rs_group }}"
        name: "{{ 'nic1' + vm_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: subnet1
        public_ip_name: "{{ 'publicip' + vnet_name }}"
        security_group: "{{ sec_gr_name }}"

  - name: Create account
    azure_rm_storageaccount:
      resource_group: "{{ rs_group }}"
      name: "{{ 'storage1' + vm_name  }}"
      account_type: "{{ acc_type }}"

  - name: Create VM with defaults
    azure_rm_virtualmachine:
        resource_group: "{{ rs_group }}"
        name: "{{ vm_name }}"
        vm_size: "{{ vm_size }}"
        storage_account: "{{ 'storage1' + vm_name }}"
        network_interfaces: "{{ 'nic1' + vm_name }}"
        admin_username: ubuntu
        admin_password: Password123456
        image:
           offer: UbuntuServer
           publisher: Canonical
           sku: '16.04-LTS'
           version: latest
